import * as assert from "assert";
import * as os from "os";
import * as path from "path";
import { promises as fs } from "fs";
import {
    findConfigForFile,
    parseRautomod,
    parseRautomodDocument,
    resolveProjectConfigAsync,
    serializeRautomodDocument
} from "../automod/automodConfigFile";

suite("rautomodConfig", () => {
    test("parses extended rule fields", () => {
        const rules = parseRautomod(`visibility=pub(crate)
sort=cfg_first
fmt=enabled
target=mod.rs
pattern=core,!tests
exclude=generated/**
group_order=cfg,pub_mod,mod,pub_use,use
blank_lines=2
reexport=enabled
header=generated by rustautomod
generated_comment=managed block`);

        assert.strictEqual(rules.length, 1);
        assert.strictEqual(rules[0].visibility, "pub(crate)");
        assert.strictEqual(rules[0].sort, "cfg_first");
        assert.strictEqual(rules[0].target, "mod.rs");
        assert.strictEqual(rules[0].reexport, "enabled");
        assert.deepStrictEqual(rules[0].pattern, ["core", "!tests"]);
        assert.deepStrictEqual(rules[0].exclude, ["generated/**"]);
        assert.deepStrictEqual(rules[0].groupOrder, ["cfg", "pub_mod", "mod", "pub_use", "use"]);
        assert.strictEqual(rules[0].blankLines, 2);
    });

    test("respects negative patterns and falls back to default rule", () => {
        const rules = parseRautomod(`pattern=core,!tests
visibility=private

visibility=pub`);

        const resolvedRule = findConfigForFile(rules, "/project/src/tests/core.rs");
        assert.strictEqual(resolvedRule?.visibility, "pub");
    });

    test("resolves extends and exclude as ignored", async () => {
        const workspacePath = await fs.mkdtemp(path.join(os.tmpdir(), "rust-automod-config-"));
        const sharedConfigPath = path.join(workspacePath, "shared.rautomod");
        const configPath = path.join(workspacePath, ".rautomod");
        const srcDir = path.join(workspacePath, "src");
        const targetPath = path.join(srcDir, "internal", "feature.rs");

        try {
            await fs.mkdir(path.dirname(targetPath), { recursive: true });
            await fs.writeFile(sharedConfigPath, "pattern=src/internal/**\nvisibility=private\n", "utf8");
            await fs.writeFile(configPath, "extends=./shared.rautomod\nexclude=src/internal/**\n", "utf8");
            await fs.writeFile(path.join(workspacePath, "Cargo.toml"), "[package]\nname=\"cfg-test\"\nversion=\"0.1.0\"\nedition=\"2021\"\n", "utf8");
            await fs.writeFile(targetPath, "pub fn demo() {}\n", "utf8");

            const resolved = await resolveProjectConfigAsync(targetPath);
            assert.strictEqual(resolved.ignored, true);
            assert.strictEqual(resolved.sourcePath, configPath);
        } finally {
            await fs.rm(workspacePath, { recursive: true, force: true });
        }
    });

    test("serializes and reparses full visual-editor fields", () => {
        const serialized = serializeRautomodDocument({
            sourcePath: "/workspace/.rautomod",
            schemaVersion: "1",
            strictMode: "error",
            extendsPaths: ["./shared.rautomod", "../preset.rautomod"],
            diagnostics: [],
            rules: [
                {
                    visibility: "pub(super)",
                    sort: "pub_first",
                    fmt: "enabled",
                    target: "main.rs",
                    pattern: ["src/api/**", "!src/api/tests/**"],
                    exclude: ["generated/**"],
                    cfg: ['feature="serde"', 'all(unix, target_pointer_width = "64")'],
                    groupOrder: ["use", "cfg", "pub_mod", "mod", "pub_use"],
                    blankLines: 2,
                    reexport: "enabled",
                    header: "generated by rustautomod",
                    generatedComment: "managed block",
                    sourcePath: "/workspace/.rautomod"
                }
            ]
        });

        const reparsed = parseRautomodDocument(serialized, "/workspace/.rautomod");

        assert.strictEqual(reparsed.schemaVersion, "1");
        assert.strictEqual(reparsed.strictMode, "error");
        assert.deepStrictEqual(reparsed.extendsPaths, ["./shared.rautomod", "../preset.rautomod"]);
        assert.strictEqual(reparsed.rules.length, 1);
        assert.strictEqual(reparsed.rules[0].visibility, "pub(super)");
        assert.strictEqual(reparsed.rules[0].sort, "pub_first");
        assert.strictEqual(reparsed.rules[0].fmt, "enabled");
        assert.strictEqual(reparsed.rules[0].target, "main.rs");
        assert.deepStrictEqual(reparsed.rules[0].pattern, ["src/api/**", "!src/api/tests/**"]);
        assert.deepStrictEqual(reparsed.rules[0].exclude, ["generated/**"]);
        assert.deepStrictEqual(reparsed.rules[0].cfg, ['feature="serde"', 'all(unix, target_pointer_width = "64")']);
        assert.deepStrictEqual(reparsed.rules[0].groupOrder, ["use", "cfg", "pub_mod", "mod", "pub_use"]);
        assert.strictEqual(reparsed.rules[0].blankLines, 2);
        assert.strictEqual(reparsed.rules[0].reexport, "enabled");
        assert.strictEqual(reparsed.rules[0].header, "generated by rustautomod");
        assert.strictEqual(reparsed.rules[0].generatedComment, "managed block");
    });

    test("preserves unmanaged blocks and leading comments when serializing visual edits", () => {
        const existing = `# team note

owner=platform

visibility=pub
sort=alpha
`;

        const serialized = serializeRautomodDocument({
            sourcePath: "/workspace/.rautomod",
            schemaVersion: "1",
            strictMode: "warn",
            extendsPaths: [],
            diagnostics: [],
            rules: [
                {
                    visibility: "private",
                    sort: "cfg_first",
                    fmt: "disabled",
                    target: "auto",
                    groupOrder: ["use", "cfg", "pub_mod", "mod", "pub_use"],
                    blankLines: 1,
                    reexport: "disabled",
                    sourcePath: "/workspace/.rautomod"
                }
            ]
        }, existing);

        assert.ok(serialized.startsWith("# team note"));
        assert.ok(serialized.includes("owner=platform"));
        assert.ok(serialized.includes("schema_version=1"));
        assert.ok(serialized.includes("strict=warn"));
        assert.ok(serialized.includes("visibility=private"));
        assert.ok(serialized.includes("sort=cfg_first"));
    });

    test("preserves comments inside managed rule blocks", () => {
        const existing = `schema_version=1
strict=warn

# visual explanation
visibility=pub
sort=alpha
`;

        const serialized = serializeRautomodDocument({
            sourcePath: "/workspace/.rautomod",
            schemaVersion: "1",
            strictMode: "error",
            extendsPaths: ["./shared.rautomod"],
            diagnostics: [],
            rules: [
                {
                    visibility: "pub(crate)",
                    sort: "pub_first",
                    fmt: "enabled",
                    target: "lib.rs",
                    groupOrder: ["use", "cfg", "pub_mod", "mod", "pub_use"],
                    blankLines: 2,
                    reexport: "enabled",
                    sourcePath: "/workspace/.rautomod"
                }
            ]
        }, existing);

        assert.ok(serialized.includes("# visual explanation"));
        assert.ok(serialized.includes("strict=error"));
        assert.ok(serialized.includes("extends=./shared.rautomod"));
        assert.ok(serialized.includes("visibility=pub(crate)"));
        assert.ok(serialized.includes("sort=pub_first"));
        assert.ok(serialized.includes("target=lib.rs"));
    });
});
