import * as assert from "assert";
import * as os from "os";
import * as path from "path";
import { promises as fs } from "fs";
import { findConfigForFile, parseRautomod, resolveProjectConfigAsync } from "../automod/automodConfigFile";

suite("rautomodConfig", () => {
    test("parses extended rule fields", () => {
        const rules = parseRautomod(`visibility=pub(crate)
sort=cfg_first
fmt=enabled
target=mod.rs
pattern=core,!tests
exclude=generated/**
group_order=cfg,pub_mod,mod,pub_use,use
blank_lines=2
reexport=enabled
header=generated by rustautomod
generated_comment=managed block`);

        assert.strictEqual(rules.length, 1);
        assert.strictEqual(rules[0].visibility, "pub(crate)");
        assert.strictEqual(rules[0].sort, "cfg_first");
        assert.strictEqual(rules[0].target, "mod.rs");
        assert.strictEqual(rules[0].reexport, "enabled");
        assert.deepStrictEqual(rules[0].pattern, ["core", "!tests"]);
        assert.deepStrictEqual(rules[0].exclude, ["generated/**"]);
        assert.deepStrictEqual(rules[0].groupOrder, ["cfg", "pub_mod", "mod", "pub_use", "use"]);
        assert.strictEqual(rules[0].blankLines, 2);
    });

    test("respects negative patterns and falls back to default rule", () => {
        const rules = parseRautomod(`pattern=core,!tests
visibility=private

visibility=pub`);

        const resolvedRule = findConfigForFile(rules, "/project/src/tests/core.rs");
        assert.strictEqual(resolvedRule?.visibility, "pub");
    });

    test("resolves extends and exclude as ignored", async () => {
        const workspacePath = await fs.mkdtemp(path.join(os.tmpdir(), "rust-automod-config-"));
        const sharedConfigPath = path.join(workspacePath, "shared.rautomod");
        const configPath = path.join(workspacePath, ".rautomod");
        const srcDir = path.join(workspacePath, "src");
        const targetPath = path.join(srcDir, "internal", "feature.rs");

        try {
            await fs.mkdir(path.dirname(targetPath), { recursive: true });
            await fs.writeFile(sharedConfigPath, "pattern=src/internal/**\nvisibility=private\n", "utf8");
            await fs.writeFile(configPath, "extends=./shared.rautomod\nexclude=src/internal/**\n", "utf8");
            await fs.writeFile(path.join(workspacePath, "Cargo.toml"), "[package]\nname=\"cfg-test\"\nversion=\"0.1.0\"\nedition=\"2021\"\n", "utf8");
            await fs.writeFile(targetPath, "pub fn demo() {}\n", "utf8");

            const resolved = await resolveProjectConfigAsync(targetPath);
            assert.strictEqual(resolved.ignored, true);
            assert.strictEqual(resolved.sourcePath, configPath);
        } finally {
            await fs.rm(workspacePath, { recursive: true, force: true });
        }
    });
});
