"use strict";

const shared = globalThis.__RUST_AUTOMOD_ZED_SHARED__ || require("./rautomod_zed_core");

const documents = new Map();
let buffered = Buffer.alloc(0);
let shutdownRequested = false;

const COMPLETION_ITEMS = {
    key: [
        completionItem("schema_version", "Document schema version", "schema_version=1", 10),
        completionItem("strict", "Validation strictness", "strict=warn", 10),
        completionItem("extends", "Inherit another config", "extends=./shared.rautomod", 10),
        completionItem("visibility", "Generated module visibility", "visibility=pub", 10),
        completionItem("sort", "Generated declaration ordering", "sort=alpha", 10),
        completionItem("fmt", "Run cargo fmt after writes", "fmt=disabled", 10),
        completionItem("target", "Choose mod.rs/lib.rs/main.rs target", "target=auto", 10),
        completionItem("pattern", "Match files or folders for this rule", "pattern=queries,!tests", 10),
        completionItem("exclude", "Ignore files or folders", "exclude=generated/**", 10),
        completionItem("cfg", "Attach cfg(...) attributes", "cfg=unix,windows", 10),
        completionItem("group_order", "Control declaration group order", "group_order=use,cfg,pub_mod,mod,pub_use", 10),
        completionItem("blank_lines", "Blank lines between groups", "blank_lines=1", 10),
        completionItem("reexport", "Enable or disable pub use generation", "reexport=disabled", 10),
        completionItem("header", "Managed header text", "header=generated by rustautomod", 10),
        completionItem("generated_comment", "Managed comment text", "generated_comment=managed by rustautomod", 10)
    ],
    visibility: [
        completionItem("pub", "Public module", "pub", 13),
        completionItem("private", "Private module", "private", 13),
        completionItem("pub(crate)", "Visible inside the crate", "pub(crate)", 13),
        completionItem("pub(super)", "Visible to the parent module", "pub(super)", 13)
    ],
    sort: [
        completionItem("alpha", "Alphabetical sort", "alpha", 13),
        completionItem("alpha_case_insensitive", "Alphabetical ignoring case", "alpha_case_insensitive", 13),
        completionItem("none", "Keep existing order", "none", 13),
        completionItem("pub_first", "Public declarations first", "pub_first", 13),
        completionItem("cfg_first", "Cfg blocks first", "cfg_first", 13)
    ],
    fmt: [
        completionItem("enabled", "Run cargo fmt", "enabled", 13),
        completionItem("disabled", "Do not run cargo fmt", "disabled", 13)
    ],
    target: [
        completionItem("auto", "Detect target automatically", "auto", 13),
        completionItem("mod.rs", "Write to local mod.rs", "mod.rs", 13),
        completionItem("lib.rs", "Write to nearest lib.rs", "lib.rs", 13),
        completionItem("main.rs", "Write to nearest main.rs", "main.rs", 13)
    ],
    strict: [
        completionItem("off", "Do not surface strict diagnostics", "off", 13),
        completionItem("warn", "Warn on config issues", "warn", 13),
        completionItem("error", "Treat config issues as blocking", "error", 13)
    ],
    reexport: [
        completionItem("enabled", "Generate re-exports", "enabled", 13),
        completionItem("disabled", "Do not generate re-exports", "disabled", 13)
    ],
    group_order: [
        completionItem("use,cfg,pub_mod,mod,pub_use", "Default group order", "use,cfg,pub_mod,mod,pub_use", 13),
        completionItem("cfg,pub_mod,mod,pub_use,use", "Cfg-first group order", "cfg,pub_mod,mod,pub_use,use", 13),
        completionItem("pub_mod,mod,pub_use,use,cfg", "Modules first", "pub_mod,mod,pub_use,use,cfg", 13)
    ],
    blank_lines: [
        completionItem("0", "No blank lines", "0", 21),
        completionItem("1", "Single blank line", "1", 21),
        completionItem("2", "Double blank line", "2", 21)
    ],
    schema_version: [
        completionItem("1", "Current schema version", "1", 21)
    ]
};

process.stdin.on("data", chunk => {
    buffered = Buffer.concat([buffered, chunk]);
    processBuffer();
});

process.stdin.on("end", () => {
    process.exit(shutdownRequested ? 0 : 1);
});

function processBuffer() {
    while (true) {
        const separatorIndex = buffered.indexOf("\r\n\r\n");
        if (separatorIndex === -1) {
            return;
        }

        const header = buffered.slice(0, separatorIndex).toString("utf8");
        const match = /Content-Length:\s*(\d+)/i.exec(header);
        if (!match) {
            buffered = Buffer.alloc(0);
            return;
        }

        const contentLength = Number(match[1]);
        const messageStart = separatorIndex + 4;
        if (buffered.length < messageStart + contentLength) {
            return;
        }

        const messageBuffer = buffered.slice(messageStart, messageStart + contentLength);
        buffered = buffered.slice(messageStart + contentLength);

        handleMessage(JSON.parse(messageBuffer.toString("utf8")));
    }
}

function handleMessage(message) {
    if (typeof message.id !== "undefined" && typeof message.method === "string") {
        handleRequest(message);
        return;
    }

    if (typeof message.method === "string") {
        handleNotification(message);
    }
}

function handleRequest(message) {
    switch (message.method) {
        case "initialize":
            sendResponse(message.id, {
                capabilities: {
                    textDocumentSync: {
                        openClose: true,
                        change: 1,
                        save: { includeText: true }
                    },
                    hoverProvider: true,
                    completionProvider: {
                        triggerCharacters: ["=", ","]
                    },
                    documentFormattingProvider: true
                },
                serverInfo: {
                    name: "Rust AutoMod Language Server",
                    version: "0.3.1"
                }
            });
            break;
        case "textDocument/hover":
            sendResponse(message.id, hoverResponse(message.params));
            break;
        case "textDocument/completion":
            sendResponse(message.id, completionResponse(message.params));
            break;
        case "textDocument/formatting":
            sendResponse(message.id, formattingResponse(message.params));
            break;
        case "shutdown":
            shutdownRequested = true;
            sendResponse(message.id, null);
            break;
        default:
            sendResponse(message.id, null);
            break;
    }
}

function handleNotification(message) {
    switch (message.method) {
        case "initialized":
            return;
        case "textDocument/didOpen":
            openDocument(message.params.textDocument);
            return;
        case "textDocument/didChange":
            changeDocument(message.params);
            return;
        case "textDocument/didSave":
            saveDocument(message.params);
            return;
        case "textDocument/didClose":
            closeDocument(message.params.textDocument);
            return;
        case "exit":
            process.exit(shutdownRequested ? 0 : 1);
            return;
        default:
            return;
    }
}

function openDocument(textDocument) {
    documents.set(textDocument.uri, {
        uri: textDocument.uri,
        version: textDocument.version || 0,
        text: textDocument.text || ""
    });
    publishDiagnostics(textDocument.uri);
}

function changeDocument(params) {
    const existing = documents.get(params.textDocument.uri);
    if (!existing) {
        return;
    }

    const latestChange = params.contentChanges[params.contentChanges.length - 1];
    existing.text = latestChange.text || "";
    existing.version = params.textDocument.version || existing.version;
    documents.set(params.textDocument.uri, existing);
    publishDiagnostics(params.textDocument.uri);
}

function saveDocument(params) {
    const existing = documents.get(params.textDocument.uri);
    if (!existing) {
        return;
    }

    if (typeof params.text === "string") {
        existing.text = params.text;
        documents.set(params.textDocument.uri, existing);
    }

    publishDiagnostics(params.textDocument.uri);
}

function closeDocument(textDocument) {
    documents.delete(textDocument.uri);
    sendNotification("textDocument/publishDiagnostics", {
        uri: textDocument.uri,
        diagnostics: []
    });
}

function publishDiagnostics(uri) {
    const document = documents.get(uri);
    if (!document) {
        return;
    }

    const parsed = shared.parseRautomodDocument(document.text, uri);
    const diagnostics = parsed.diagnostics.map(diagnostic => toLspDiagnostic(document.text, diagnostic));

    sendNotification("textDocument/publishDiagnostics", {
        uri,
        diagnostics
    });
}

function hoverResponse(params) {
    const document = documents.get(params.textDocument.uri);
    if (!document) {
        return null;
    }

    const lineText = getLine(document.text, params.position.line);
    const key = extractKeyFromLine(lineText);
    const info = tokenAt(lineText, params.position.character);

    if (!info) {
        return null;
    }

    if (info.kind === "key") {
        const detail = shared.RAUTOMOD_KEY_DETAILS[info.value];
        if (!detail) {
            return null;
        }
        return {
            contents: {
                kind: "markdown",
                value: `**${info.value}**\n\n${detail}`
            }
        };
    }

    if (info.kind === "value" && key) {
        const detail = valueHover(key, info.value);
        if (!detail) {
            return null;
        }
        return {
            contents: {
                kind: "markdown",
                value: detail
            }
        };
    }

    return null;
}

function completionResponse(params) {
    const document = documents.get(params.textDocument.uri);
    if (!document) {
        return [];
    }

    const lineText = getLine(document.text, params.position.line);
    const beforeCursor = lineText.slice(0, params.position.character);
    const separatorIndex = lineText.indexOf("=");
    const editingKey = separatorIndex === -1 || params.position.character <= separatorIndex;
    const items = editingKey
        ? COMPLETION_ITEMS.key
        : COMPLETION_ITEMS[extractKeyFromLine(lineText)] || [];

    const prefix = currentTokenPrefix(beforeCursor);
    return items
        .filter(item => !prefix || item.label.startsWith(prefix) || (item.insertText || "").startsWith(prefix))
        .map(item => withCompletionRange(item, params.position, prefix));
}

function formattingResponse(params) {
    const document = documents.get(params.textDocument.uri);
    if (!document) {
        return [];
    }

    const formatted = shared.formatRautomod(document.text);
    if (formatted === document.text) {
        return [];
    }

    return [{
        range: fullDocumentRange(document.text),
        newText: formatted
    }];
}

function sendResponse(id, result) {
    writeMessage({
        jsonrpc: "2.0",
        id,
        result
    });
}

function sendNotification(method, params) {
    writeMessage({
        jsonrpc: "2.0",
        method,
        params
    });
}

function writeMessage(payload) {
    const serialized = JSON.stringify(payload);
    const header = `Content-Length: ${Buffer.byteLength(serialized, "utf8")}\r\n\r\n`;
    process.stdout.write(header);
    process.stdout.write(serialized);
}

function getLine(text, lineNumber) {
    const lines = String(text || "").replace(/\r\n/g, "\n").split("\n");
    return lines[lineNumber] || "";
}

function currentTokenPrefix(beforeCursor) {
    const match = /([A-Za-z0-9_().!\/\\*:-]+)$/.exec(beforeCursor);
    return match ? match[1] : "";
}

function extractKeyFromLine(lineText) {
    const separatorIndex = lineText.indexOf("=");
    if (separatorIndex === -1) {
        return "";
    }
    return lineText.slice(0, separatorIndex).trim();
}

function tokenAt(lineText, character) {
    const separatorIndex = lineText.indexOf("=");
    if (separatorIndex === -1 || character <= separatorIndex) {
        const key = lineText.slice(0, separatorIndex === -1 ? lineText.length : separatorIndex).trim();
        return key ? { kind: "key", value: key } : null;
    }

    const value = lineText.slice(separatorIndex + 1).trim();
    if (!value) {
        return null;
    }

    const segments = value
        .split(",")
        .map(segment => segment.trim())
        .filter(Boolean);
    return segments.length > 0 ? { kind: "value", value: segments[0] } : null;
}

function toLspDiagnostic(text, diagnostic) {
    const lineText = getLine(text, diagnostic.line);
    const key = extractKeyFromLine(lineText);
    const startCharacter = Math.max(0, lineText.indexOf(key));
    const endCharacter = Math.max(startCharacter + 1, lineText.length);

    return {
        range: {
            start: { line: diagnostic.line, character: startCharacter },
            end: { line: diagnostic.line, character: endCharacter }
        },
        severity: diagnostic.severity === "error" ? 1 : 2,
        code: diagnostic.code,
        source: "rustautomod",
        message: diagnostic.message
    };
}

function completionItem(label, detail, insertText, kind) {
    return {
        label,
        detail,
        insertText,
        kind
    };
}

function withCompletionRange(item, position, prefix) {
    if (!prefix) {
        return item;
    }

    return {
        ...item,
        textEdit: {
            range: {
                start: {
                    line: position.line,
                    character: Math.max(0, position.character - prefix.length)
                },
                end: {
                    line: position.line,
                    character: position.character
                }
            },
            newText: item.insertText || item.label
        }
    };
}

function fullDocumentRange(text) {
    const normalized = String(text || "").replace(/\r\n/g, "\n");
    const lines = normalized.split("\n");
    const lastLine = Math.max(0, lines.length - 1);
    const lastCharacter = lines[lastLine] ? lines[lastLine].length : 0;

    return {
        start: { line: 0, character: 0 },
        end: { line: lastLine, character: lastCharacter }
    };
}

function valueHover(key, value) {
    switch (key) {
        case "visibility":
            return `**${value}**\n\nControls the Rust visibility modifier used in generated module declarations.`;
        case "sort":
            return `**${value}**\n\nControls the ordering strategy for generated declarations.`;
        case "fmt":
            return `**${value}**\n\nDetermines whether Rust AutoMod should run \`cargo fmt\` after writes.`;
        case "target":
            return `**${value}**\n\nDetermines where the generated declaration should be written.`;
        case "strict":
            return `**${value}**\n\nControls whether config problems are ignored, warned, or treated as blocking.`;
        case "reexport":
            return `**${value}**\n\nControls whether Rust AutoMod should generate re-exports alongside module declarations.`;
        case "schema_version":
            return `**${value}**\n\nCurrent .rautomod schema version.`;
        default:
            return null;
    }
}
